### ISSUE TITLE
No results in Variant Report

### ISSUE THREAD

**Issue by Eduardo-Auer** [KarchinLab/open-cravat#60]
I noticed that the Variant report shows no results after specifying a variant that I would like to report. The command that I used was: `http://localhost:8080/result/nocache/variant.html?chrom=chr6&pos=32045210&ref_base=A&alt_base=G`

I also attached the image below with the results page, which is shown to me.
![Sem título](https://user-images.githubusercontent.com/79405348/109540697-9a2e9700-7aa1-11eb-8bbe-f90ce7ae1295.png)

**Comment by rkiminsilico** [comment]
@Eduardo-Auer Thanks for letting us know. The server has been fixed.

**Comment by Eduardo-Auer** [comment]
Unfortunately, the issue still the same. I have a doubt. I found this variant using hg38 genome reference in vcf annotation analysis. Perhaps, it would be the problem?

**Comment by rkimoakbioinformatics** [comment]
@Eduardo-Auer Sorry that I missed the fact that you were using the local installation of OpenCRAVAT. Please update the modules with one of the two following methods:

1. If your OpenCRAVAT is not version 2.2.3, run `pip install open-cravat --upgrade` on a terminal to upgrade OpenCRAVAT. Then, run `oc module update` on the terminal. Then, run `oc gui` and try the same URL.

2. If your OpenCRAVAT is not version 2.2.3, run `pip install open-cravat --upgrade` on a terminal to upgrade OpenCRAVAT. Then, run `oc gui` and when the OpenCRAVAT GUI opens on a browser, go to the `Store` tab. At the top of the right panel (above module tiles) will `Updates to your installed modules are available!` message and `Update All` button be. Press the button to update widget modules. Then, try the same URL.

**Comment by Eduardo-Auer** [comment]
@rkimoakbioinformatics I have updated OpenCRAVAT to version 2.2.3 and its modules are all updated too. However, I am experiencing the same error.

**Comment by rkimoakbioinformatics** [comment]
@Eduardo-Auer I see. For debugging purposes, can you let me know the output of the following?

1. On the command-line, `oc module ls -a -i`
2. On the browser, as you get the error on a browser tab, open the JavaScript console of the development tool and copy and paste any error messages on the console.

**Comment by Eduardo-Auer** [comment]
@rkimoakbioinformatics Sure, no problem. I will send the JavaScript console error and the `oc module ls -a -i` logs.

[JavaScript console error.log](https://github.com/KarchinLab/open-cravat/files/6069617/JavaScript.console.error.log)
[oc module ls -a -i log.txt](https://github.com/KarchinLab/open-cravat/files/6069618/oc.module.ls.-a.-i.log.txt)

**Comment by rkimoakbioinformatics** [comment]
@Eduardo-Auer Thanks. Some modules needed for the variant report page were not installed in your system. We'll improve the handling of requirements in the future. Sorry for the inconvenience. The necessary modules are:
```
hg38
chasmplus
civic
cosmic
cgc
cgl
target
gnomad
thousandgenomes
hgdp
esp6500
abraom
uk10k_cohort
pharmgkb
clinvar
clingen
denovo
gwas_catalog
ess_gene
gnomad_gene
prec
phi
ghis
loftool
interpro
gtex
rvis
ncbigene
vest
mutpred1
mutation_assessor
fathmm
phdsnpg
phastcons
phylop
linsight
ncrna
pseudogene
biogrid
intact
ndex
mupit
```

If you have access to the command line `oc`, the following command will install (if a module is already installed it will be skipped) necessary modules. 

```
oc module install -y hg38 chasmplus civic cosmic cgc cgl target gnomad thousandgenomes hgdp esp6500 abraom uk10k_cohort pharmgkb clinvar clingen denovo gwas_catalog ess_gene gnomad_gene prec phi ghis loftool interpro gtex rvis ncbigene vest mutpred1 mutation_assessor fathmm phdsnpg phastcons phylop linsight ncrna pseudogene biogrid intact ndex mupit
```

Let me know if it solves the issue.

**Comment by Eduardo-Auer** [comment]
Ok. I have run the command: `oc module install -y hg38 chasmplus civic cosmic cgc cgl target gnomad thousandgenomes hgdp esp6500 abraom uk10k_cohort pharmgkb clinvar clingen denovo gwas_catalog ess_gene gnomad_gene prec phi ghis loftool interpro gtex rvis ncbigene vest mutpred1 mutation_assessor fathmm phdsnpg phastcons phylop linsight ncrna pseudogene biogrid intact ndex mupit`.

After running the command:
```
C:\Program Files (x86)\open-cravat\scripts>oc module install -y hg38 chasmplus civic cosmic cgc cgl target gnomad thousandgenomes hgdp esp6500 abraom uk10k_cohort pharmgkb clinvar clingen denovo gwas_catalog ess_gene gnomad_gene prec phi ghis loftool interpro gtex rvis ncbigene vest mutpred1 mutation_assessor fathmm phdsnpg phastcons phylop linsight ncrna pseudogene biogrid intact ndex mupit
abraom: latest (1.0.0) is already installed. Use -f/--force to overwrite
biogrid: latest (3.6.0) is already installed. Use -f/--force to overwrite
cgc: latest (85.0.12) is already installed. Use -f/--force to overwrite
cgl: latest (1.1.0) is already installed. Use -f/--force to overwrite
chasmplus: latest (1.3.0) is already installed. Use -f/--force to overwrite
civic: latest (1.0.15) is already installed. Use -f/--force to overwrite
clingen: latest (1.0.1) is already installed. Use -f/--force to overwrite
clinvar: latest (2021.02.04) is already installed. Use -f/--force to overwrite
cosmic: latest (92.1.0) is already installed. Use -f/--force to overwrite
denovo: latest (1.6.11) is already installed. Use -f/--force to overwrite
esp6500: latest (6500.2.6) is already installed. Use -f/--force to overwrite
ess_gene: latest (3.5.8) is already installed. Use -f/--force to overwrite
fathmm: latest (2.3.6) is already installed. Use -f/--force to overwrite
ghis: latest (3.6.0) is already installed. Use -f/--force to overwrite
gnomad: latest (2.2.0) is already installed. Use -f/--force to overwrite
gnomad_gene: latest (2.2.1) is already installed. Use -f/--force to overwrite
gtex: latest (7.0.4) is already installed. Use -f/--force to overwrite
gwas_catalog: latest (1.0.0) is already installed. Use -f/--force to overwrite
hg38: latest (1.10.2) is already installed. Use -f/--force to overwrite
hgdp: latest (1.0.0) is already installed. Use -f/--force to overwrite
intact: latest (2019.08.23) is already installed. Use -f/--force to overwrite
interpro: latest (71.3.0) is already installed. Use -f/--force to overwrite
linsight: latest (2021.01.08) is already installed. Use -f/--force to overwrite
loftool: latest (3.6.1) is already installed. Use -f/--force to overwrite
mupit: latest (4.3.3) is already installed. Use -f/--force to overwrite
mutation_assessor: latest (3.0.6) is already installed. Use -f/--force to overwrite
mutpred1: latest (1.4.0) is already installed. Use -f/--force to overwrite
ncbigene: latest (2019.08.02) is already installed. Use -f/--force to overwrite
ncrna: latest (2019.08.19) is already installed. Use -f/--force to overwrite
ndex: latest (4.0.11) is already installed. Use -f/--force to overwrite
pharmgkb: latest (2.0.0) is already installed. Use -f/--force to overwrite
phastcons: latest (3.5.8) is already installed. Use -f/--force to overwrite
phdsnpg: latest (0.0.8) is already installed. Use -f/--force to overwrite
phi: latest (3.6.1) is already installed. Use -f/--force to overwrite
phylop: latest (3.5.9) is already installed. Use -f/--force to overwrite
prec: latest (3.6.0) is already installed. Use -f/--force to overwrite
pseudogene: latest (28.0.1) is already installed. Use -f/--force to overwrite
rvis: latest (3.1.0) is already installed. Use -f/--force to overwrite
target: latest (3.1.0) is already installed. Use -f/--force to overwrite
thousandgenomes: latest (4.1.0) is already installed. Use -f/--force to overwrite
uk10k_cohort: latest (3.5.9) is already installed. Use -f/--force to overwrite
vest: latest (4.3.1) is already installed. Use -f/--force to overwrite
No modules to install found
```
Besides, the issue is still happening. Do you know other cause which might be producing this issue?

**Comment by rkimoakbioinformatics** [comment]
@Eduardo-Auer It seems that `wghgvs` module is not installed in your system. Please try with `oc module install wghgvs`.

**Comment by Eduardo-Auer** [comment]
@rkimoakbioinformatics I am deeply grateful for your help! It worked! I think you solved this issue. I noticed another thing. It is about the variant annotations pathogenicity predictions. I have a variant with results in DANN Coding, MetaLR, MetaSNV, MutationTaster and MutPred. Still, it does not show these results on Variant Report. Is it because the report of these pathogenicity predictions is not supported?

**Comment by Eduardo-Auer** [comment]
@rkimoakbioinformatics  I am deeply grateful for your help! It worked! I think you solved this issue. I noticed another thing. It is about the variant annotations pathogenicity predictions. I have a variant with results from CADD exome, DANN Coding, MetaLR, MetaSNV, MutationTaster, PhD-SNPg, PROVEAN, REVEL, SIFT and MutationAssessor. Still, it does not show these results on Variant Report. Is it because the report of these pathogenicity predictions is not supported?

**Comment by rkimoakbioinformatics** [comment]
@Eduardo-Auer That's great. 

Regarding the missing annotation results, they are missing mostly because they were published after the variant report page had been made. Thus, the variant report page needs some catching up. Also, we carefully choose annotators in designing the variant report page. Requests for including specific annotator results in the variant report page from users are important to us. We'll discuss including them and let you know any update.

**Comment by Eduardo-Auer** [comment]
@rkimoakbioinformatics Thank you for your quick response! I believe you answered and solved all doubts and issues that I had.
Best regards,
Eduardo.

**Comment by rkimoakbioinformatics** [comment]
@Eduardo-Auer That's great. When we add more annotator modules to the variant report page, we'll let you know on this thread.
